# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

markdown: kramdown 

# Setup
title:               PhD. Eng. Marcelo Forets
tagline:             'Researcher in Applied Mathematics'
description:         'Post-doc researcher at VERIMAG group from Univ. Grenoble Alpes, France.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marcelo-forets.fr/" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  mforets

# this is the number of posts that are shown at the same time in the Home page. In general it is used in index.html 
paginate:            4

# About/contact
author:
  name:              marcelo forets
  url:               https://marcelo-forets.fr/
  email:             marcelo.forets@imag.fr

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
