# Site Info
title:               PhD. Eng. Marcelo Forets
tagline:             'Researcher in Applied Mathematics. Developer.'
description:         'Associate Professor at UTEC, Uruguay, and former post-doc researcher at VERIMAG group from Univ. Grenoble Alpes, France.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mforets.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Site Configuration
gems:
    - jekyll-paginate
markdown: kramdown
# this is the number of posts that are shown at the same time in the Home page. In general it is used in index.html
paginate:            8
version:             1.0.0
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty


# About/contact
github_username:  mforets
author:
  name:              marcelo forets
  url:               http://mforets.github.io
  email:             mforets@gmail.com
  contact:
    linkedin:  https://www.linkedin.com/in/marcelo-forets-irurtia-7b8238149/
    github:    https://github.com/mforets
    gitlab:    https://gitlab.com/mforets
    facebook:  https://www.facebook.com/marcelo.forets
    email:     http://www.google.com/recaptcha/mailhide/d?k=01YFZZ3JLUy71TNQftCaGYpA==&c=85E2iFWOo5smBeLRQV4ZaVHFsMlBA_QjzQ4rIo23QIY=

# Plugins
mathjax: true # whether support mathjax
google_analytics_token: # 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: # 'your_short_name' # leave blank if you don't want disqus
